title: "Latheesh Kumar E"
email: Latheesh720@live.com
description: >- # this means to ignore newlines until "baseurl:"
  This is my portfolio website!
baseurl: "/" 
url: "latheesh.github.io" 
twitter_username: mlhacks
github_username:  mlh-fellowship

sass:
  sass_dir: _sass

icon: /assets/img/icon.jpg
